export const data = [
  {
    rank: 1,
    token: 'USDC.e + USDT.e',
    transactions: 0.997,
    tvl: '176.7k',
    volume24h: '-',
    volume7d: '-',
    apr: 1.0,
  },
  {
    rank: 2,
    token: 'USDC.e + USDT.e',
    transactions: 0.997,
    tvl: '176.7k',
    volume24h: '-',
    volume7d: '-',
    apr: 1.0,
  },
  {
    rank: 3,
    token: 'USDC.e + USDT.e',
    transactions: 0.997,
    tvl: '176.7k',
    volume24h: '-',
    volume7d: '-',
    apr: 1.0,
  },
  {
    rank: 4,
    token: 'USDC.e + USDT.e',
    transactions: 0.997,
    tvl: '176.7k',
    volume24h: '-',
    volume7d: '-',
    apr: 1.0,
  },
  {
    rank: 5,
    token: 'USDC.e + USDT.e',
    transactions: 0.997,
    tvl: '176.7k',
    volume24h: '-',
    volume7d: '-',
    apr: 1.0,
  },
];
